# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'justpayng' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for justpayng
  pod 'Firebase/Core', '~> 5.9.0'
  pod 'Firebase/Auth', '~> 5.9.0'
  pod 'Firebase/Messaging', '~> 5.9.0'
  target 'justpayng-tvOSTests' do
    inherit! :search_paths
    # Pods for testing

    pod 'ReactNativePermissions', :path => '../node_modules/react-native-permissions'

    pod 'react-native-contacts', :path => '../node_modules/react-native-contacts'

    pod 'react-native-camera', :path => '../node_modules/react-native-camera'

  end

  target 'justpayngTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
